import type { ExamCurriculum } from '../types'

export const bcsPreliminaryCurriculum: ExamCurriculum = {
  exam: {
    slug: 'bcs',
    stage: 'preliminary',
    name: 'বাংলাদেশ সিভিল সার্ভিস (BCS)',
    stageName: 'প্রিলিমিনারি টেস্ট',
    totalMarks: 200,
  },
  subjects: [
    {
      id: 'bcs-01-bangla',
      order: 1,
      name: 'বাংলা ভাষা ও সাহিত্য',
      marks: 30,
      sections: [
        {
          id: 'bcs-01-bangla-language',
          order: 1,
          name: 'ভাষা',
          marks: 15,
          topics: [
            {
              id: 'bcs-01-bangla-language-topic',
              order: 1,
              name: 'প্রয়োগ-অপপ্রয়োগ, বানান ও বাক্য শুদ্ধি, পরিভাষা, সমার্থক ও বিপরীতার্থক শব্দ, ধ্বনি, বর্ণ, শব্দ, পদ, বাক্য, প্রত্যয়, সন্ধি ও সমাস',
              description: '১৫ নম্বর',
            },
          ],
        },
        {
          id: 'bcs-01-bangla-literature',
          order: 2,
          name: 'সাহিত্য',
          marks: 15,
          topics: [
            {
              id: 'bcs-01-bangla-lit-ancient',
              order: 1,
              name: 'ক. প্রাচীন ও মধ্যযুগ',
              marks: 5,
              description: '০৫ নম্বর',
              subtopics: [],
            },
            {
              id: 'bcs-01-bangla-lit-modern',
              order: 2,
              name: 'খ. আধুনিক যুগ (১৮০০-বর্তমান পর্যন্ত)',
              marks: 10,
              description: '১০ নম্বর',
              subtopics: [],
            },
          ],
        },
      ],
    },
    {
      id: 'bcs-02-english',
      order: 2,
      name: 'English Language and Literature',
      marks: 30,
      sections: [
        {
          id: 'bcs-02-english-language',
          order: 1,
          name: 'PART-I: Language',
          marks: 15,
          topics: [
            {
              id: 'bcs-02-english-pos',
              order: 1,
              name: 'A. Parts of Speech',
              subtopics: [
                { id: 'bcs-02-english-pos-01', order: 1, name: 'The Noun' },
                { id: 'bcs-02-english-pos-02', order: 2, name: 'The Determiner' },
                { id: 'bcs-02-english-pos-03', order: 3, name: 'The Gender' },
                { id: 'bcs-02-english-pos-04', order: 4, name: 'The Number' },
                { id: 'bcs-02-english-pos-05', order: 5, name: 'The Pronoun' },
                { id: 'bcs-02-english-pos-06', order: 6, name: 'The Verb' },
                { id: 'bcs-02-english-pos-07', order: 7, name: 'The Finite: transitive, intransitive' },
                { id: 'bcs-02-english-pos-08', order: 8, name: 'The Non-finite: participles, infinitives, gerund' },
                { id: 'bcs-02-english-pos-09', order: 9, name: 'The Linking Verb' },
                { id: 'bcs-02-english-pos-10', order: 10, name: 'The Phrasal Verb' },
                { id: 'bcs-02-english-pos-11', order: 11, name: 'Modals' },
                { id: 'bcs-02-english-pos-12', order: 12, name: 'The Adjective' },
                { id: 'bcs-02-english-pos-13', order: 13, name: 'The Adverb' },
                { id: 'bcs-02-english-pos-14', order: 14, name: 'The Preposition' },
                { id: 'bcs-02-english-pos-15', order: 15, name: 'The Conjunction' },
              ],
            },
            {
              id: 'bcs-02-english-idioms',
              order: 2,
              name: 'B. Idioms & Phrases',
              subtopics: [
                { id: 'bcs-02-english-idioms-01', order: 1, name: 'Meanings of Phrases' },
                { id: 'bcs-02-english-idioms-02', order: 2, name: 'Kinds of Phrases' },
                { id: 'bcs-02-english-idioms-03', order: 3, name: 'Identifying Phrases' },
              ],
            },
            {
              id: 'bcs-02-english-clauses',
              order: 3,
              name: 'C. Clauses',
              subtopics: [
                { id: 'bcs-02-english-clauses-01', order: 1, name: 'The Principal Clause' },
                { id: 'bcs-02-english-clauses-02', order: 2, name: 'The Subordinate Clause' },
                { id: 'bcs-02-english-clauses-03', order: 3, name: 'The Noun Clause' },
                { id: 'bcs-02-english-clauses-04', order: 4, name: 'The Adjective Clause' },
                { id: 'bcs-02-english-clauses-05', order: 5, name: 'The Adverbial Clause & its types' },
              ],
            },
            {
              id: 'bcs-02-english-corrections',
              order: 4,
              name: 'D. Corrections',
              subtopics: [
                { id: 'bcs-02-english-corrections-01', order: 1, name: 'The Tense' },
                { id: 'bcs-02-english-corrections-02', order: 2, name: 'The Verb' },
                { id: 'bcs-02-english-corrections-03', order: 3, name: 'The Preposition' },
                { id: 'bcs-02-english-corrections-04', order: 4, name: 'The Determiner' },
                { id: 'bcs-02-english-corrections-05', order: 5, name: 'The Gender' },
                { id: 'bcs-02-english-corrections-06', order: 6, name: 'The Number' },
                { id: 'bcs-02-english-corrections-07', order: 7, name: 'Subject-Verb Agreement' },
              ],
            },
            {
              id: 'bcs-02-english-sentences',
              order: 5,
              name: 'E. Sentences & Transformations',
              subtopics: [
                { id: 'bcs-02-english-sentences-01', order: 1, name: 'The Simple Sentence' },
                { id: 'bcs-02-english-sentences-02', order: 2, name: 'The Compound Sentence' },
                { id: 'bcs-02-english-sentences-03', order: 3, name: 'The Complex Sentence' },
                { id: 'bcs-02-english-sentences-04', order: 4, name: 'The Active Voice' },
                { id: 'bcs-02-english-sentences-05', order: 5, name: 'The Passive Voice' },
                { id: 'bcs-02-english-sentences-06', order: 6, name: 'The Positive Degree' },
                { id: 'bcs-02-english-sentences-07', order: 7, name: 'The Comparative Degree' },
                { id: 'bcs-02-english-sentences-08', order: 8, name: 'The Superlative Degree' },
              ],
            },
            {
              id: 'bcs-02-english-words',
              order: 6,
              name: 'F. Words',
              subtopics: [
                { id: 'bcs-02-english-words-01', order: 1, name: 'Meanings' },
                { id: 'bcs-02-english-words-02', order: 2, name: 'Synonyms' },
                { id: 'bcs-02-english-words-03', order: 3, name: 'Antonyms' },
                { id: 'bcs-02-english-words-04', order: 4, name: 'Spellings' },
                { id: 'bcs-02-english-words-05', order: 5, name: 'Usage of words as various parts of speech' },
                { id: 'bcs-02-english-words-06', order: 6, name: 'Formation of new words by adding prefixes and suffixes' },
              ],
            },
            {
              id: 'bcs-02-english-composition',
              order: 7,
              name: 'G. Composition',
              subtopics: [
                { id: 'bcs-02-english-composition-01', order: 1, name: 'Names of parts of paragraphs/letters/applications' },
              ],
            },
          ],
        },
        {
          id: 'bcs-02-english-literature',
          order: 2,
          name: 'PART-II: Literature',
          marks: 15,
          topics: [
            {
              id: 'bcs-02-english-lit-topic',
              order: 1,
              name: 'H. English Literature',
              subtopics: [
                {
                  id: 'bcs-02-english-lit-01',
                  order: 1,
                  name: 'Names of writers of literary pieces from Elizabethan period to the 21st Century.',
                },
                {
                  id: 'bcs-02-english-lit-02',
                  order: 2,
                  name: 'Quotations from drama/poetry of different ages.',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'bcs-03-bangladesh-affairs',
      order: 3,
      name: 'বাংলাদেশ বিষয়াবলি',
      marks: 25,
      sections: [
        {
          id: 'bcs-03-bd-01',
          order: 1,
          name: '১. বাংলাদেশের জাতীয় বিষয়াবলি',
          marks: 6,
          description: 'প্রাচীনকাল হতে সম-সাময়িক কালের ইতিহাস, কৃষ্টি ও সংস্কৃতি। ভাষা আন্দোলন; ১৯৫৪ সালের নির্বাচন; গণ অভ্যুত্থান ১৯৬৯: বাংলাদেশের স্বাধীনতা সংগ্রাম ও মহান মুক্তিযুদ্ধের ইতিহাস; মুক্তিযুদ্ধের রণকৌশল; মুক্তিযুদ্ধে বৃহৎ শক্তিবর্গের ভূমিকা; পাকিস্তানী বাহিনীর আত্মসমর্পণ এবং বাংলাদেশের অভ্যুদয় ।',
        },
        {
          id: 'bcs-03-bd-02',
          order: 2,
          name: '২. বাংলাদেশের কৃষিজ সম্পদ',
          marks: 2,
          description: 'শস্য উৎপাদন এবং এর বহুমুখীকরণ, খাদ্য উৎপাদন ও ব্যবস্থাপনা ।',
        },
        {
          id: 'bcs-03-bd-03',
          order: 3,
          name: '৩. জনসংখ্যা',
          marks: 2,
          description: 'বাংলাদেশের জনসংখ্যা, জনশুমারি, জাতি, গোষ্ঠী ও ক্ষুদ্র নৃগোষ্ঠী সংক্রান্ত বিষয়াদি ।',
        },
        {
          id: 'bcs-03-bd-04',
          order: 4,
          name: '৪. বাংলাদেশের অর্থনীতি',
          marks: 2,
          description: 'উন্নয়ন পরিকল্পনা প্রেক্ষিত, জাতীয় আয়-ব্যয়, রাজনীতি ও বার্ষিক উন্নয়ন কর্মসূচি, দারিদ্র্য বিমোচন ইত্যাদি ।',
        },
        {
          id: 'bcs-03-bd-05',
          order: 5,
          name: '৫. বাংলাদেশের শিল্প ও বাণিজ্য',
          marks: 2,
          description: 'শিল্প উৎপাদন, পণ্য আমদানি ও রপ্তানিকরণ, গার্মেন্টস শিল্প ও এর সার্বিক ব্যবস্থাপনা, অন্যান্য শিল্পসমূহ, বৈদেশিক লেন-দেন, অর্থ প্রেরণ, ব্যাংক ও বীমা ব্যবস্থাপনা ইত্যাদি ।',
        },
        {
          id: 'bcs-03-bd-06',
          order: 6,
          name: '৬. বাংলাদেশের সংবিধান',
          marks: 3,
          description: 'প্রস্তাবনা ও বৈশিষ্ট্য, মৌলিক অধিকারসহ রাষ্ট্র পরিচালনার মূলনীতিসমূহ, সংবিধানের সংশোধনীসমূহ ।',
        },
        {
          id: 'bcs-03-bd-07',
          order: 7,
          name: '৭. বাংলাদেশের রাজনৈতিক ব্যবস্থা',
          marks: 3,
          description: 'রাজনৈতিক দলসমূহের পঠন, ভূমিকা ও কার্যক্রম, ক্ষমতাসীন ও বিরোধী দলের পারস্পরিক সম্পর্কাদি, সুশীল সমাজ ও চাপ সৃষ্টিকারী গোষ্ঠীসমূহ এবং এদের ভূমিকা ।',
        },
        {
          id: 'bcs-03-bd-08',
          order: 8,
          name: '৮. বাংলাদেশের সরকার ব্যবস্থা',
          marks: 3,
          description: 'আইন, শাসন ও বিচার বিভাগসমূহ, আইন প্রণয়ন, নীতি নির্ধারণ, জাতীয় ও স্থানীয় পর্যায়ের প্রশাসনিক ব্যবস্থাপনা কাঠামো, প্রশাসনিক পুনর্বিন্যাস ও সংস্কার; স্থানীয় সরকার ব্যবস্থাপনা ।',
        },
        {
          id: 'bcs-03-bd-09',
          order: 9,
          name: '৯. জাতীয় বিষয়াদি',
          marks: 2,
          description: 'বাংলাদেশের জাতীয় অর্জন, বিশিষ্ট ব্যক্তিত্ব, গুরুত্বপূর্ণ প্রতিষ্ঠানসমূহ, জাতীয় পুরস্কার, বাংলাদেশের খেলাধুলাসহ চলচ্চিত্র, গণমাধ্যম-সংশ্লিষ্ট বিষয়াদি ।',
        },
      ],
    },
    {
      id: 'bcs-04-international',
      order: 4,
      name: 'আন্তর্জাতিক বিষয়াবলি',
      marks: 25,
      sections: [
        {
          id: 'bcs-04-int-01',
          order: 1,
          name: '১. বৈশ্বিক ইতিহাস, আঞ্চলিক ও আন্তর্জাতিক ব্যবস্থা, ভূ-রাজনীতি',
          marks: 5,
          description: '০৫ নম্বর',
        },
        {
          id: 'bcs-04-int-02',
          order: 2,
          name: '২. আন্তর্জাতিক নিরাপত্তা ও আন্তরাষ্ট্রীয় ক্ষমতা সম্পর্ক',
          marks: 5,
          description: '০৫ নম্বর',
        },
        {
          id: 'bcs-04-int-03',
          order: 3,
          name: '৩. বিশ্বের সাম্প্রতিক ও চলমান ঘটনাপ্রবাহ',
          marks: 5,
          description: '০৫ নম্বর',
        },
        {
          id: 'bcs-04-int-04',
          order: 4,
          name: '৪. আন্তর্জাতিক পরিবেশগত ইস্যু ও কূটনীতি',
          marks: 5,
          description: '০৫ নম্বর',
        },
        {
          id: 'bcs-04-int-05',
          order: 5,
          name: '৫. আন্তর্জাতিক সংগঠনসমূহ এবং বৈশ্বিক অর্থনৈতিক প্রতিষ্ঠানাদি',
          marks: 5,
          description: '০৫ নম্বর',
        },
      ],
    },
    {
      id: 'bcs-05-geography',
      order: 5,
      name: 'ভূগোল (বাংলাদেশ ও বিশ্ব), পরিবেশ ও দুর্যোগ ব্যবস্থাপনা',
      marks: 10,
      sections: [
        {
          id: 'bcs-05-geo-01',
          order: 1,
          name: '১. বাংলাদেশ ও অঞ্চলভিত্তিক ভৌগোলিক অবস্থান, সীমানা, পারিবেশিক, আর্থ-সামাজিক ও ভূ-রাজনৈতিক গুরুত্ব',
          marks: 2,
          description: '০২ নম্বর',
        },
        {
          id: 'bcs-05-geo-02',
          order: 2,
          name: '২. অঞ্চলভিত্তিক ভৌত পরিবেশ (ভূ-প্রাকৃতিক), সম্পদের বণ্টন ও গুরুত্ব',
          marks: 2,
          description: '০২ নম্বর',
        },
        {
          id: 'bcs-05-geo-03',
          order: 3,
          name: '৩. বাংলাদেশের পরিবেশ: প্রকৃতি ও সম্পদ, প্রধান চ্যালেঞ্জসমূহ',
          marks: 2,
          description: '০২ নম্বর',
        },
        {
          id: 'bcs-05-geo-04',
          order: 4,
          name: '৪. বাংলাদেশ ও বৈশ্বিক পরিবেশ পরিবর্তন: আবহাওয়া ও জলবায়ু নিয়ামকসমূহের সেক্টরভিত্তিক (যেমন অভিবাসন, কৃষি, শিল্প, মৎস্য ইত্যাদি) স্থানীয়, আঞ্চলিক ও বৈশ্বিক প্রভাব',
          marks: 2,
          description: '০২ নম্বর',
        },
        {
          id: 'bcs-05-geo-05',
          order: 5,
          name: '৫. প্রাকৃতিক দুর্যোগ ও ব্যবস্থাপনা: দুর্যোগের ধরন, প্রকৃতি ও ব্যবস্থাপনা',
          marks: 2,
          description: '০২ নম্বর',
        },
      ],
    },
    {
      id: 'bcs-06-general-science',
      order: 6,
      name: 'সাধারণ বিজ্ঞান',
      marks: 15,
      sections: [
        {
          id: 'bcs-06-sci-physics',
          order: 1,
          name: 'ভৌত বিজ্ঞান',
          marks: 5,
          description: '০৫ নম্বর',
          topics: [
            {
              id: 'bcs-06-sci-physics-topic',
              order: 1,
              name: 'পদার্থের অবস্থা, এটমের গঠন, কার্বনের বহুমুখী ব্যবহার, এসিড, ক্ষার, লবণ, পদার্থের ক্ষয়, সাবানের কাজ, ভৌত রাশি এবং এর পরিমাপ, ভৌত বিজ্ঞানের উন্নয়ন, চৌম্বকত্ব, তরঙ্গ এবং শব্দ, তাপ ও তাপগতি বিদ্যা, আলোর প্রকৃতি, স্থির এবং চল তড়িৎ, ইলেকট্রনিক্স, আধুনিক পদার্থবিজ্ঞান, শক্তির উৎস এবং এর প্রয়োগ, নবায়নযোগ্য শক্তির উৎস, পারমাণবিক শক্তি, খনিজ উৎস, শক্তির রূপান্তর, আলোক যন্ত্রপাতি, মৌলিক কণা, ধাতব পদার্থ এবং তাদের যৌগসমূহ, অধাতব পদার্থ, জারণ-বিজারণ, তড়িৎ কোষ, অজৈব যৌগ, জৈব যৌগ, তড়িৎ চৌম্বক, ট্রান্সফরমার, এক্সরে, তেজস্ক্রিয়তা ইত্যাদি ।',
            },
          ],
        },
        {
          id: 'bcs-06-sci-biology',
          order: 2,
          name: 'জীব বিজ্ঞান',
          marks: 5,
          description: '০৫ নম্বর',
          topics: [
            {
              id: 'bcs-06-sci-biology-topic',
              order: 1,
              name: 'পদার্থের জীববিজ্ঞান-বিষয়ক ধর্ম, টিস্যু, জেনেটিকস, জীববৈচিত্র্য, এনিম্যাল ডাইভারসিটি, প্লান্ট ডাইভারসিটি, এনিম্যাল টিস্যু, অর্গান এবং অর্গান সিস্টেম, সালোক সংশ্লেষণ, ভাইরাস, ব্যাকটেরিয়া, জুলোজিক্যাল নমেনক্লেচার, বোটানিক্যাল নমেনক্রেচার, প্রাণিজগৎ, উদ্ভিদ, ফুল, ফল, রক্ত ও রক্ত সঞ্চালন, রক্তচাপ, হৃদপিণ্ড এবং হৃদরোগ, স্নায়ু এবং স্নায়ুরোগ, খাদ্য ও পুষ্টি, ভিটামিন, মাইক্রোবায়োলজি, প্লান্ট নিউট্রেশন, পরাগায়ন ইত্যাদি ।',
            },
          ],
        },
        {
          id: 'bcs-06-sci-modern',
          order: 3,
          name: 'আধুনিক বিজ্ঞান',
          marks: 5,
          description: '০৫ নম্বর',
          topics: [
            {
              id: 'bcs-06-sci-modern-topic',
              order: 1,
              name: 'পৃথিবী সৃষ্টির ইতিহাস, কসমিক রে, ব্লাক হোল, হিগের কণা, বারিমণ্ডল, টাইড, বায়ুমণ্ডল, টেকটোনিক প্লেট, সাইক্লোন, সুনামি, বিবর্তন, সামুদ্রিক জীবন, মানবদেহ, রোগের কারণ ও প্রতিকার, সংক্রামক রোগ, রোগ জীবাণুর জীবনধারণ, মা ও শিশু স্বাস্থ্য, ইম্যুনাইজেশন এবং ভ্যাকসিনেশন, এইচআইভি, এইডস, টিবি, পোলিও, জোয়ার-ভাটা, এপিকালচার, সেরিকালচার, পিসিকালচার, হর্টিকালচার, ডায়োড, ট্রানজিস্টর, আইসি, আপেক্ষিক তত্তা, ফোটন কণা ইত্যাদি ।',
            },
          ],
        },
      ],
    },
    {
      id: 'bcs-07-computer',
      order: 7,
      name: 'কম্পিউটার ও তথ্য প্রযুক্তি',
      marks: 15,
      sections: [
        {
          id: 'bcs-07-comp',
          order: 1,
          name: 'কম্পিউটার',
          marks: 10,
          topics: [
            {
              id: 'bcs-07-comp-topic',
              order: 1,
              name: 'কম্পিউটার পেরিফেরালস (Computer Peripherals): কি-বোর্ড (Keyboard), মাউস (Mouse), ওসিআর (OCR) ইত্যাদি । কম্পিউটারের অঙ্গসংগঠন (Computer Architecture): সিপিইউ (CPU), হার্ড ডিস্ক (Hard Disk, এএলইউ (ALU) ইত্যাদি । কম্পিউটারের পারঙ্গমতা (Computer Performance) । দৈনন্দিন জীবনে কম্পিউটার (Computer in Practical Fields): কৃষি, যোগাযোগ, শিক্ষা, স্বাস্থ্য, খেলাধুলা ইত্যাদি । কম্পিউটারের নম্বর ব্যবস্থা (Number Systems of Computer) । অপারেটিং সিস্টেমস (Operating Systems) । এমবেডেড কম্পিউটার (Embedded Computer) । কম্পিউটারের ইতিহাস (History of Computer) । কম্পিউটারের প্রকারভেদ (Types of Computers) । কম্পিউটার প্রোগ্রাম (Computer Program): ভাইরাস (VIRUS), ফায়ারওয়াল (Firewall) ইত্যাদি । ডেটাবেইস সিস্টেম (Database System) ।',
            },
          ],
        },
        {
          id: 'bcs-07-ict',
          order: 2,
          name: 'তথ্যপ্রযুক্তি',
          marks: 5,
          topics: [
            {
              id: 'bcs-07-ict-topic',
              order: 1,
              name: 'ই-কমার্স (E-Commerce) । সেলুলার ডাটা নেটওয়ার্ক (Cellular Data Network): টুজি (2G), থ্রিজি (3G), ফোরজি (4G), ওয়াইম্যাক্স (Wimax) ইত্যাদি । কম্পিউটার নেটওয়ার্ক (Computer Network): ল্যান (LAN), ম্যান (MAN), ওয়াই-ফাই (WiFi), ওয়াইম্যাক্স (Wimax) ইত্যাদি । দৈনন্দিন জীবনে তথ্যপ্রযুক্তি (Information Technologies in Practical Fields) । স্মার্টফোন (SmartPhone) । ওয়ার্ল্ড ওয়াইড ওয়েব (World Wide Web WWW) । ইন্টারনেট (Internet) । নিত্য প্রয়োজনীয় কম্পিউটিং প্রযুক্তি (Daily-Use Computing Technology): ই-মেইল (E-mail), ফ্যাক্স (Fax) ইত্যাদি । ক্লায়ন্ট-সার্ভার ম্যানেজমেন্ট (Client-Server Management) । মোবাইল প্রযুক্তির বৈশিষ্ট্যসমূহ (Mobile Features) । তথ্যপ্রযুক্তির বড় প্রতিষ্ঠান ও তাদের সেবা/তথ্যসমূহ (Tech-Giants Services & News): গুগল (Google), মাইক্রোসফট (Microsoft), আইবিএম (IBM) ইত্যাদি । ক্লাউড কম্পিউটিং (Cloud Computing) । সোশ্যাল নেটওয়ার্কিং (Social Networking): ফেসবুক (Facebook), টুইটার (Instagram), ইন্সটাগ্রাম (Twitter) ইত্যাদি । রোবটিক্স (Robotics) । সাইবার অপরাধ (Cyber Crime) ।',
            },
          ],
        },
      ],
    },
    {
      id: 'bcs-08-math',
      order: 8,
      name: 'গাণিতিক যুক্তি',
      marks: 20,
      sections: [
        {
          id: 'bcs-08-math-01',
          order: 1,
          name: '১. বাস্তব সংখ্যা, ল.সা.গু, গ.সা.গু, শতকরা, সরল ও যৌগিক মুনাফা, অনুপাত ও সমানুপাত, লাভ ও ক্ষতি',
          marks: 4,
          description: '০৪/08',
        },
        {
          id: 'bcs-08-math-02',
          order: 2,
          name: '২. বীজগাণিতিক সূত্রাবলি, বহুপদী উৎপাদক, সরল ও দ্বিপদী সমীকরণ, সরল ও দ্বিপদী অসমতা, সরল সহসমীকরণ',
          marks: 4,
          description: '০৪/08',
        },
        {
          id: 'bcs-08-math-03',
          order: 3,
          name: '৩. সূচক ও লগারিদম, সমান্তর ও গুণোত্তর অনুক্রম ও ধারা',
          marks: 4,
          description: '০৪',
        },
        {
          id: 'bcs-08-math-04',
          order: 4,
          name: '৪. রেখা, কোণ, ত্রিভুজ ও চতুর্ভুজ সংক্রান্ত উপপাদ্য, পিথাগোরাসের উপপাদ্য, বৃত্ত সংক্রান্ত উপপাদ্য, পরিমিতি- সরলক্ষেত্র ও ঘনবস্তু',
          marks: 4,
          description: '০৪/08',
        },
        {
          id: 'bcs-08-math-05',
          order: 5,
          name: '৫. সেট, বিন্যাস ও সমাবেশ, পরিসংখ্যান ও সম্ভাব্যতা',
          marks: 4,
          description: '০৪/08',
        },
      ],
    },
    {
      id: 'bcs-09-mental',
      order: 9,
      name: 'মানসিক দক্ষতা',
      marks: 15,
      sections: [
        {
          id: 'bcs-09-mental-01',
          order: 1,
          name: '১. ভাষাগত যৌক্তিক বিচার (Verbal Reasoning)',
          marks: 0,
        },
        {
          id: 'bcs-09-mental-02',
          order: 2,
          name: '২. সমস্যা সমাধান (Problem Solving)',
          marks: 0,
        },
        {
          id: 'bcs-09-mental-03',
          order: 3,
          name: '৩. বানান ও ভাষা (Spelling and Language)',
          marks: 0,
        },
        {
          id: 'bcs-09-mental-04',
          order: 4,
          name: '৪. যান্ত্রিক দক্ষতা (Mechanical Reasoning)',
          marks: 0,
        },
        {
          id: 'bcs-09-mental-05',
          order: 5,
          name: '৫. স্থানাঙ্ক সম্পর্ক (Space Relation)',
          marks: 0,
        },
        {
          id: 'bcs-09-mental-06',
          order: 6,
          name: '৬. সংখ্যাগত ক্ষমতা (Numerical Ability)',
          marks: 0,
        },
      ],
    },
    {
      id: 'bcs-10-ethics',
      order: 10,
      name: 'নৈতিকতা, মূল্যবোধ ও সু-শাসন',
      marks: 15,
      sections: [
        {
          id: 'bcs-10-ethics-01',
          order: 1,
          name: 'Definition of Values and Good Governance',
          marks: 0,
        },
        {
          id: 'bcs-10-ethics-02',
          order: 2,
          name: 'Relation between Values and Good Governance',
          marks: 0,
        },
        {
          id: 'bcs-10-ethics-03',
          order: 3,
          name: 'General Perception of Values and Good Governance: Importance of Values and Good Governance in the life of an individual as a citizen as well as in the making of society and national ideals: Impact of Values and Good Governance in national development; How the element of Good Governance and Values can be established in society in a given social context; The benefit of Values and Good Governance and the cost society pays adversely in their absence.',
          marks: 0,
        },
      ],
    },
  ],
}
